// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/login": {
    params: {};
  };
  "/forgot-password": {
    params: {};
  };
  "/reset-password": {
    params: {};
  };
  "/employee/dashboard": {
    params: {};
  };
  "/employee/attendance": {
    params: {};
  };
  "/employee/attendance/history": {
    params: {};
  };
  "/employee/attendance/:id": {
    params: {
      "id": string;
    };
  };
  "/employee/attendance/late-request": {
    params: {};
  };
  "/employee/leave": {
    params: {};
  };
  "/employee/leave/apply": {
    params: {};
  };
  "/employee/leave/apply-emergency": {
    params: {};
  };
  "/employee/leave/:id": {
    params: {
      "id": string;
    };
  };
  "/employee/salary": {
    params: {};
  };
  "/employee/salary/breakdown": {
    params: {};
  };
  "/employee/salary/:id": {
    params: {
      "id": string;
    };
  };
  "/employee/loans": {
    params: {};
  };
  "/employee/loans/apply": {
    params: {};
  };
  "/employee/loans/:id": {
    params: {
      "id": string;
    };
  };
  "/employee/performance": {
    params: {};
  };
  "/employee/performance/goal": {
    params: {};
  };
  "/employee/performance/review/:id": {
    params: {
      "id": string;
    };
  };
  "/employee/performance/feedback/:id": {
    params: {
      "id": string;
    };
  };
  "/employee/policies": {
    params: {};
  };
  "/employee/policies/:slug": {
    params: {
      "slug": string;
    };
  };
  "/employee/profile": {
    params: {};
  };
  "/employee/profile/edit": {
    params: {};
  };
  "/employee/profile/change-password": {
    params: {};
  };
  "/employee/profile/shift-change": {
    params: {};
  };
  "/employee/notifications": {
    params: {};
  };
  "/team/dashboard": {
    params: {};
  };
  "/team/approvals": {
    params: {};
  };
  "/team/approvals/:id": {
    params: {
      "id": string;
    };
  };
  "/team/performance": {
    params: {};
  };
  "/team/reports": {
    params: {};
  };
  "/team/members/:id": {
    params: {
      "id": string;
    };
  };
  "/team/members/add": {
    params: {};
  };
  "/admin/dashboard": {
    params: {};
  };
  "/admin/employees": {
    params: {};
  };
  "/admin/employees/new": {
    params: {};
  };
  "/admin/employees/:id": {
    params: {
      "id": string;
    };
  };
  "/admin/employees/:id/edit": {
    params: {
      "id": string;
    };
  };
  "/admin/attendance": {
    params: {};
  };
  "/admin/leave": {
    params: {};
  };
  "/admin/leave/:id": {
    params: {
      "id": string;
    };
  };
  "/admin/leave/new": {
    params: {};
  };
  "/admin/leave/emergency": {
    params: {};
  };
  "/admin/payroll": {
    params: {};
  };
  "/admin/payroll/salary-config": {
    params: {};
  };
  "/admin/bonuses": {
    params: {};
  };
  "/admin/loans": {
    params: {};
  };
  "/admin/loans/:id": {
    params: {
      "id": string;
    };
  };
  "/admin/performance": {
    params: {};
  };
  "/admin/recruitment": {
    params: {};
  };
  "/admin/recruitment/jobs/:id": {
    params: {
      "id": string;
    };
  };
  "/admin/recruitment/candidates/:id": {
    params: {
      "id": string;
    };
  };
  "/admin/policies": {
    params: {};
  };
  "/admin/integrations": {
    params: {};
  };
  "/admin/office-config": {
    params: {};
  };
  "/admin/reports": {
    params: {};
  };
  "/*": {
    params: {
      "*": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/login" | "/forgot-password" | "/reset-password" | "/employee/dashboard" | "/employee/attendance" | "/employee/attendance/history" | "/employee/attendance/:id" | "/employee/attendance/late-request" | "/employee/leave" | "/employee/leave/apply" | "/employee/leave/apply-emergency" | "/employee/leave/:id" | "/employee/salary" | "/employee/salary/breakdown" | "/employee/salary/:id" | "/employee/loans" | "/employee/loans/apply" | "/employee/loans/:id" | "/employee/performance" | "/employee/performance/goal" | "/employee/performance/review/:id" | "/employee/performance/feedback/:id" | "/employee/policies" | "/employee/policies/:slug" | "/employee/profile" | "/employee/profile/edit" | "/employee/profile/change-password" | "/employee/profile/shift-change" | "/employee/notifications" | "/team/dashboard" | "/team/approvals" | "/team/approvals/:id" | "/team/performance" | "/team/reports" | "/team/members/:id" | "/team/members/add" | "/admin/dashboard" | "/admin/employees" | "/admin/employees/new" | "/admin/employees/:id" | "/admin/employees/:id/edit" | "/admin/attendance" | "/admin/leave" | "/admin/leave/:id" | "/admin/leave/new" | "/admin/leave/emergency" | "/admin/payroll" | "/admin/payroll/salary-config" | "/admin/bonuses" | "/admin/loans" | "/admin/loans/:id" | "/admin/performance" | "/admin/recruitment" | "/admin/recruitment/jobs/:id" | "/admin/recruitment/candidates/:id" | "/admin/policies" | "/admin/integrations" | "/admin/office-config" | "/admin/reports" | "/*";
  };
  "components/layouts/GuestLayout.tsx": {
    id: "components/layouts/GuestLayout";
    page: "/" | "/login" | "/forgot-password" | "/reset-password";
  };
  "pages/redirect-home.tsx": {
    id: "pages/redirect-home";
    page: "/";
  };
  "pages/auth/Login.tsx": {
    id: "pages/auth/Login";
    page: "/login";
  };
  "pages/auth/ForgotPassword.tsx": {
    id: "pages/auth/ForgotPassword";
    page: "/forgot-password";
  };
  "pages/auth/ResetPassword.tsx": {
    id: "pages/auth/ResetPassword";
    page: "/reset-password";
  };
  "components/layouts/EmployeeLayout.tsx": {
    id: "components/layouts/EmployeeLayout";
    page: "/employee/dashboard" | "/employee/attendance" | "/employee/attendance/history" | "/employee/attendance/:id" | "/employee/attendance/late-request" | "/employee/leave" | "/employee/leave/apply" | "/employee/leave/apply-emergency" | "/employee/leave/:id" | "/employee/salary" | "/employee/salary/breakdown" | "/employee/salary/:id" | "/employee/loans" | "/employee/loans/apply" | "/employee/loans/:id" | "/employee/performance" | "/employee/performance/goal" | "/employee/performance/review/:id" | "/employee/performance/feedback/:id" | "/employee/policies" | "/employee/policies/:slug" | "/employee/profile" | "/employee/profile/edit" | "/employee/profile/change-password" | "/employee/profile/shift-change" | "/employee/notifications";
  };
  "pages/employee/Dashboard.tsx": {
    id: "pages/employee/Dashboard";
    page: "/employee/dashboard";
  };
  "pages/employee/AttendanceMain.tsx": {
    id: "pages/employee/AttendanceMain";
    page: "/employee/attendance";
  };
  "pages/employee/AttendanceHistory.tsx": {
    id: "pages/employee/AttendanceHistory";
    page: "/employee/attendance/history";
  };
  "pages/employee/AttendanceDetail.tsx": {
    id: "pages/employee/AttendanceDetail";
    page: "/employee/attendance/:id";
  };
  "pages/employee/LateAttendanceRequest.tsx": {
    id: "pages/employee/LateAttendanceRequest";
    page: "/employee/attendance/late-request";
  };
  "pages/employee/LeaveMain.tsx": {
    id: "pages/employee/LeaveMain";
    page: "/employee/leave";
  };
  "pages/employee/ApplyLeave.tsx": {
    id: "pages/employee/ApplyLeave";
    page: "/employee/leave/apply";
  };
  "pages/employee/ApplyEmergencyLeave.tsx": {
    id: "pages/employee/ApplyEmergencyLeave";
    page: "/employee/leave/apply-emergency";
  };
  "pages/employee/LeaveRequestDetail.tsx": {
    id: "pages/employee/LeaveRequestDetail";
    page: "/employee/leave/:id";
  };
  "pages/employee/SalaryMain.tsx": {
    id: "pages/employee/SalaryMain";
    page: "/employee/salary";
  };
  "pages/employee/SalaryBreakdown.tsx": {
    id: "pages/employee/SalaryBreakdown";
    page: "/employee/salary/breakdown";
  };
  "pages/employee/PayslipDetail.tsx": {
    id: "pages/employee/PayslipDetail";
    page: "/employee/salary/:id";
  };
  "pages/employee/LoansMain.tsx": {
    id: "pages/employee/LoansMain";
    page: "/employee/loans";
  };
  "pages/employee/ApplyLoan.tsx": {
    id: "pages/employee/ApplyLoan";
    page: "/employee/loans/apply";
  };
  "pages/employee/LoanDetail.tsx": {
    id: "pages/employee/LoanDetail";
    page: "/employee/loans/:id";
  };
  "pages/employee/Performance.tsx": {
    id: "pages/employee/Performance";
    page: "/employee/performance";
  };
  "pages/employee/GoalCreateEdit.tsx": {
    id: "pages/employee/GoalCreateEdit";
    page: "/employee/performance/goal";
  };
  "pages/employee/ReviewDetail.tsx": {
    id: "pages/employee/ReviewDetail";
    page: "/employee/performance/review/:id";
  };
  "pages/employee/FeedbackDetail.tsx": {
    id: "pages/employee/FeedbackDetail";
    page: "/employee/performance/feedback/:id";
  };
  "pages/employee/Policies.tsx": {
    id: "pages/employee/Policies";
    page: "/employee/policies";
  };
  "pages/employee/PolicyDetail.tsx": {
    id: "pages/employee/PolicyDetail";
    page: "/employee/policies/:slug";
  };
  "pages/employee/Profile.tsx": {
    id: "pages/employee/Profile";
    page: "/employee/profile";
  };
  "pages/employee/EditProfile.tsx": {
    id: "pages/employee/EditProfile";
    page: "/employee/profile/edit";
  };
  "pages/employee/ChangePassword.tsx": {
    id: "pages/employee/ChangePassword";
    page: "/employee/profile/change-password";
  };
  "pages/employee/ShiftChange.tsx": {
    id: "pages/employee/ShiftChange";
    page: "/employee/profile/shift-change";
  };
  "pages/employee/Notifications.tsx": {
    id: "pages/employee/Notifications";
    page: "/employee/notifications";
  };
  "components/layouts/TeamLeaderLayout.tsx": {
    id: "components/layouts/TeamLeaderLayout";
    page: "/team/dashboard" | "/team/approvals" | "/team/approvals/:id" | "/team/performance" | "/team/reports" | "/team/members/:id" | "/team/members/add";
  };
  "pages/team/Dashboard.tsx": {
    id: "pages/team/Dashboard";
    page: "/team/dashboard";
  };
  "pages/team/Approvals.tsx": {
    id: "pages/team/Approvals";
    page: "/team/approvals";
  };
  "pages/team/ApprovalDetail.tsx": {
    id: "pages/team/ApprovalDetail";
    page: "/team/approvals/:id";
  };
  "pages/team/Performance.tsx": {
    id: "pages/team/Performance";
    page: "/team/performance";
  };
  "pages/team/Reports.tsx": {
    id: "pages/team/Reports";
    page: "/team/reports";
  };
  "pages/team/MemberDetail.tsx": {
    id: "pages/team/MemberDetail";
    page: "/team/members/:id";
  };
  "pages/team/AddMember.tsx": {
    id: "pages/team/AddMember";
    page: "/team/members/add";
  };
  "components/layouts/AdminLayout.tsx": {
    id: "components/layouts/AdminLayout";
    page: "/admin/dashboard" | "/admin/employees" | "/admin/employees/new" | "/admin/employees/:id" | "/admin/employees/:id/edit" | "/admin/attendance" | "/admin/leave" | "/admin/leave/:id" | "/admin/leave/new" | "/admin/leave/emergency" | "/admin/payroll" | "/admin/payroll/salary-config" | "/admin/bonuses" | "/admin/loans" | "/admin/loans/:id" | "/admin/performance" | "/admin/recruitment" | "/admin/recruitment/jobs/:id" | "/admin/recruitment/candidates/:id" | "/admin/policies" | "/admin/integrations" | "/admin/office-config" | "/admin/reports";
  };
  "pages/admin/Dashboard.tsx": {
    id: "pages/admin/Dashboard";
    page: "/admin/dashboard";
  };
  "pages/admin/EmployeeList.tsx": {
    id: "pages/admin/EmployeeList";
    page: "/admin/employees";
  };
  "pages/admin/EmployeeCreate.tsx": {
    id: "pages/admin/EmployeeCreate";
    page: "/admin/employees/new";
  };
  "pages/admin/EmployeeDetail.tsx": {
    id: "pages/admin/EmployeeDetail";
    page: "/admin/employees/:id";
  };
  "pages/admin/EmployeeEdit.tsx": {
    id: "pages/admin/EmployeeEdit";
    page: "/admin/employees/:id/edit";
  };
  "pages/admin/AttendanceManagement.tsx": {
    id: "pages/admin/AttendanceManagement";
    page: "/admin/attendance";
  };
  "pages/admin/LeaveManagement.tsx": {
    id: "pages/admin/LeaveManagement";
    page: "/admin/leave";
  };
  "pages/admin/LeaveRequestDetail.tsx": {
    id: "pages/admin/LeaveRequestDetail";
    page: "/admin/leave/:id";
  };
  "pages/admin/CreateLeaveRequest.tsx": {
    id: "pages/admin/CreateLeaveRequest";
    page: "/admin/leave/new";
  };
  "pages/admin/EmergencyLeaveDashboard.tsx": {
    id: "pages/admin/EmergencyLeaveDashboard";
    page: "/admin/leave/emergency";
  };
  "pages/admin/PayrollManagement.tsx": {
    id: "pages/admin/PayrollManagement";
    page: "/admin/payroll";
  };
  "pages/admin/SalaryConfiguration.tsx": {
    id: "pages/admin/SalaryConfiguration";
    page: "/admin/payroll/salary-config";
  };
  "pages/admin/BonusManagement.tsx": {
    id: "pages/admin/BonusManagement";
    page: "/admin/bonuses";
  };
  "pages/admin/LoanManagement.tsx": {
    id: "pages/admin/LoanManagement";
    page: "/admin/loans";
  };
  "pages/admin/LoanDetail.tsx": {
    id: "pages/admin/LoanDetail";
    page: "/admin/loans/:id";
  };
  "pages/admin/PerformanceAdmin.tsx": {
    id: "pages/admin/PerformanceAdmin";
    page: "/admin/performance";
  };
  "pages/admin/RecruitmentManagement.tsx": {
    id: "pages/admin/RecruitmentManagement";
    page: "/admin/recruitment";
  };
  "pages/admin/JobPostingDetail.tsx": {
    id: "pages/admin/JobPostingDetail";
    page: "/admin/recruitment/jobs/:id";
  };
  "pages/admin/CandidateDetail.tsx": {
    id: "pages/admin/CandidateDetail";
    page: "/admin/recruitment/candidates/:id";
  };
  "pages/admin/PolicyManagement.tsx": {
    id: "pages/admin/PolicyManagement";
    page: "/admin/policies";
  };
  "pages/admin/IntegrationSettings.tsx": {
    id: "pages/admin/IntegrationSettings";
    page: "/admin/integrations";
  };
  "pages/admin/OfficeConfiguration.tsx": {
    id: "pages/admin/OfficeConfiguration";
    page: "/admin/office-config";
  };
  "pages/admin/ReportsExport.tsx": {
    id: "pages/admin/ReportsExport";
    page: "/admin/reports";
  };
  "pages/not-found.tsx": {
    id: "pages/not-found";
    page: "/*";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "components/layouts/GuestLayout": typeof import("./app/components/layouts/GuestLayout.tsx");
  "pages/redirect-home": typeof import("./app/pages/redirect-home.tsx");
  "pages/auth/Login": typeof import("./app/pages/auth/Login.tsx");
  "pages/auth/ForgotPassword": typeof import("./app/pages/auth/ForgotPassword.tsx");
  "pages/auth/ResetPassword": typeof import("./app/pages/auth/ResetPassword.tsx");
  "components/layouts/EmployeeLayout": typeof import("./app/components/layouts/EmployeeLayout.tsx");
  "pages/employee/Dashboard": typeof import("./app/pages/employee/Dashboard.tsx");
  "pages/employee/AttendanceMain": typeof import("./app/pages/employee/AttendanceMain.tsx");
  "pages/employee/AttendanceHistory": typeof import("./app/pages/employee/AttendanceHistory.tsx");
  "pages/employee/AttendanceDetail": typeof import("./app/pages/employee/AttendanceDetail.tsx");
  "pages/employee/LateAttendanceRequest": typeof import("./app/pages/employee/LateAttendanceRequest.tsx");
  "pages/employee/LeaveMain": typeof import("./app/pages/employee/LeaveMain.tsx");
  "pages/employee/ApplyLeave": typeof import("./app/pages/employee/ApplyLeave.tsx");
  "pages/employee/ApplyEmergencyLeave": typeof import("./app/pages/employee/ApplyEmergencyLeave.tsx");
  "pages/employee/LeaveRequestDetail": typeof import("./app/pages/employee/LeaveRequestDetail.tsx");
  "pages/employee/SalaryMain": typeof import("./app/pages/employee/SalaryMain.tsx");
  "pages/employee/SalaryBreakdown": typeof import("./app/pages/employee/SalaryBreakdown.tsx");
  "pages/employee/PayslipDetail": typeof import("./app/pages/employee/PayslipDetail.tsx");
  "pages/employee/LoansMain": typeof import("./app/pages/employee/LoansMain.tsx");
  "pages/employee/ApplyLoan": typeof import("./app/pages/employee/ApplyLoan.tsx");
  "pages/employee/LoanDetail": typeof import("./app/pages/employee/LoanDetail.tsx");
  "pages/employee/Performance": typeof import("./app/pages/employee/Performance.tsx");
  "pages/employee/GoalCreateEdit": typeof import("./app/pages/employee/GoalCreateEdit.tsx");
  "pages/employee/ReviewDetail": typeof import("./app/pages/employee/ReviewDetail.tsx");
  "pages/employee/FeedbackDetail": typeof import("./app/pages/employee/FeedbackDetail.tsx");
  "pages/employee/Policies": typeof import("./app/pages/employee/Policies.tsx");
  "pages/employee/PolicyDetail": typeof import("./app/pages/employee/PolicyDetail.tsx");
  "pages/employee/Profile": typeof import("./app/pages/employee/Profile.tsx");
  "pages/employee/EditProfile": typeof import("./app/pages/employee/EditProfile.tsx");
  "pages/employee/ChangePassword": typeof import("./app/pages/employee/ChangePassword.tsx");
  "pages/employee/ShiftChange": typeof import("./app/pages/employee/ShiftChange.tsx");
  "pages/employee/Notifications": typeof import("./app/pages/employee/Notifications.tsx");
  "components/layouts/TeamLeaderLayout": typeof import("./app/components/layouts/TeamLeaderLayout.tsx");
  "pages/team/Dashboard": typeof import("./app/pages/team/Dashboard.tsx");
  "pages/team/Approvals": typeof import("./app/pages/team/Approvals.tsx");
  "pages/team/ApprovalDetail": typeof import("./app/pages/team/ApprovalDetail.tsx");
  "pages/team/Performance": typeof import("./app/pages/team/Performance.tsx");
  "pages/team/Reports": typeof import("./app/pages/team/Reports.tsx");
  "pages/team/MemberDetail": typeof import("./app/pages/team/MemberDetail.tsx");
  "pages/team/AddMember": typeof import("./app/pages/team/AddMember.tsx");
  "components/layouts/AdminLayout": typeof import("./app/components/layouts/AdminLayout.tsx");
  "pages/admin/Dashboard": typeof import("./app/pages/admin/Dashboard.tsx");
  "pages/admin/EmployeeList": typeof import("./app/pages/admin/EmployeeList.tsx");
  "pages/admin/EmployeeCreate": typeof import("./app/pages/admin/EmployeeCreate.tsx");
  "pages/admin/EmployeeDetail": typeof import("./app/pages/admin/EmployeeDetail.tsx");
  "pages/admin/EmployeeEdit": typeof import("./app/pages/admin/EmployeeEdit.tsx");
  "pages/admin/AttendanceManagement": typeof import("./app/pages/admin/AttendanceManagement.tsx");
  "pages/admin/LeaveManagement": typeof import("./app/pages/admin/LeaveManagement.tsx");
  "pages/admin/LeaveRequestDetail": typeof import("./app/pages/admin/LeaveRequestDetail.tsx");
  "pages/admin/CreateLeaveRequest": typeof import("./app/pages/admin/CreateLeaveRequest.tsx");
  "pages/admin/EmergencyLeaveDashboard": typeof import("./app/pages/admin/EmergencyLeaveDashboard.tsx");
  "pages/admin/PayrollManagement": typeof import("./app/pages/admin/PayrollManagement.tsx");
  "pages/admin/SalaryConfiguration": typeof import("./app/pages/admin/SalaryConfiguration.tsx");
  "pages/admin/BonusManagement": typeof import("./app/pages/admin/BonusManagement.tsx");
  "pages/admin/LoanManagement": typeof import("./app/pages/admin/LoanManagement.tsx");
  "pages/admin/LoanDetail": typeof import("./app/pages/admin/LoanDetail.tsx");
  "pages/admin/PerformanceAdmin": typeof import("./app/pages/admin/PerformanceAdmin.tsx");
  "pages/admin/RecruitmentManagement": typeof import("./app/pages/admin/RecruitmentManagement.tsx");
  "pages/admin/JobPostingDetail": typeof import("./app/pages/admin/JobPostingDetail.tsx");
  "pages/admin/CandidateDetail": typeof import("./app/pages/admin/CandidateDetail.tsx");
  "pages/admin/PolicyManagement": typeof import("./app/pages/admin/PolicyManagement.tsx");
  "pages/admin/IntegrationSettings": typeof import("./app/pages/admin/IntegrationSettings.tsx");
  "pages/admin/OfficeConfiguration": typeof import("./app/pages/admin/OfficeConfiguration.tsx");
  "pages/admin/ReportsExport": typeof import("./app/pages/admin/ReportsExport.tsx");
  "pages/not-found": typeof import("./app/pages/not-found.tsx");
};